CREATE USER "admin" WITH PASSWORD 'admin';

CREATE DATABASE "triviaties";
GRANT ALL PRIVILEGES ON DATABASE "triviaties" TO "admin";

ALTER DATABASE "triviaties" OWNER TO "admin";
GRANT ALL PRIVILEGES ON SCHEMA public TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "admin";